DROP TABLE `folder`;
DROP TABLE `folderholder`;
DROP TABLE `filmreel`;
DROP TABLE `filmreelholder`;
DROP TABLE `inbox`;
ALTER TABLE `category` RENAME TO `folder` ;
ALTER TABLE `categoryholder` RENAME TO `folderholder` ;
ALTER TABLE `imageversion` RENAME TO `mediaobject` ;
ALTER TABLE `pinpic` RENAME TO `pin` ;
ALTER TABLE `pinpicholder` RENAME TO `pinholder` ;
ALTER TABLE `pinholder` CHANGE COLUMN `pinpicid` `pinid` INT(11) NOT NULL DEFAULT '0' ;
ALTER TABLE `pin` CHANGE COLUMN `pinpicid` `pinid` INT(11) NOT NULL , CHANGE COLUMN `pinpictitle` `pintitle` VARCHAR(100) NOT NULL , CHANGE COLUMN `pinpicname` `pinname` VARCHAR(100) NOT NULL ;
ALTER TABLE `mediaobject` CHANGE COLUMN `imagenumber` `medianumber` VARCHAR(255) NOT NULL DEFAULT '' ;
ALTER TABLE `mediaobject` DROP COLUMN `imageid`, DROP COLUMN `version`, DROP INDEX `imageid_index` ;
